version: '3.8'

services:
  server:
    container_name: cm-server
    hostname: cm-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GO_VER=${GO_VER}
        - ALPINE_VER=${ALPINE_VER}
        - APP_NAME=${SERVER_APP_NAME}
    env_file:
      - ./.env
    networks:
      - cm-internal-network
      - cm-external-network
    ports:
      - ${HTTP_SERVER_LISTEN_PORT}:${HTTP_SERVER_LISTEN_PORT}

  web:
    container_name: cm-web
    hostname: cm-web
    restart: unless-stopped
    depends_on:
      - server
    image: nginx:${NGINX_VER}-alpine${ALPINE_VER}
    volumes:
      - ${WEB_LOCAL_DIR}:/usr/share/nginx/html
    networks:
      - cm-external-network
    ports:
      - ${WEB_PORT}:80

networks:
  cm-internal-network:
    name: cm-internal-network
    driver: bridge
    internal: true

  cm-external-network:
    name: cm-external-network
    driver: bridge
    internal: false
