version: '3.8'

services:
  server:
    container_name: enig-server
    hostname: enig-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GO_VER=${GO_VER}
        - ALPINE_VER=${ALPINE_VER}
        - APP_NAME=${SERVER_APP_NAME}
    env_file:
      - ./.env
    networks:
      - enig-internal-network
      - enig-external-network
    ports:
      - ${HTTP_SERVER_LISTEN_PORT}:${HTTP_SERVER_LISTEN_PORT}

  web:
    container_name: enig-web
    hostname: enig-web
    restart: unless-stopped
    depends_on:
      - server
    image: nginx:${NGINX_VER}-alpine${ALPINE_VER}
    volumes:
      - ${WEB_LOCAL_DIR}:/usr/share/nginx/html
    networks:
      - enig-external-network
    ports:
      - ${WEB_PORT}:80

networks:
  enig-internal-network:
    name: enig-internal-network
    driver: bridge
    internal: true

  enig-external-network:
    name: enig-external-network
    driver: bridge
    internal: false
